import type { Knex } from "knex"

export async function seed(knex: Knex): Promise<void> {
  await knex('exercises').del();
  await knex('exercises').insert([
    // Bodyweight exercises
    {
      id: knex.raw('gen_random_uuid()'),
      name: 'Air Squat',
      slug: 'air-squat',
      description: 'Squat au poids du corps.',
      instructions: 'Pieds largeur des épaules, descendre en gardant le dos droit.',
      category: 'strength',
      muscle_groups: JSON.stringify(['legs', 'core']),
      difficulty: 'beginner',
      scaling_options: JSON.stringify(['box squat']),
      equipment_required: JSON.stringify([]),
      bodyweight_only: true,
      measurement_type: 'reps',
      contraindications: JSON.stringify(['douleur genou']),
      safety_notes: 'Ne pas arrondir le dos.',
      video_url: null,
      image_url: null,
      isActive: true
    },
    {
      id: knex.raw('gen_random_uuid()'),
      name: 'Pull-Up',
      slug: 'pull-up',
      description: 'Traction à la barre fixe.',
      instructions: 'Saisir la barre, tirer le menton au-dessus de la barre.',
      category: 'gymnastics',
      muscle_groups: JSON.stringify(['back', 'arms']),
      difficulty: 'intermediate',
      scaling_options: JSON.stringify(['banded pull-up', 'jumping pull-up']),
      equipment_required: JSON.stringify(['pull-up-bar']),
      bodyweight_only: true,
      measurement_type: 'reps',
      contraindications: JSON.stringify(['épaule instable']),
      safety_notes: 'Contrôler la descente.',
      video_url: null,
      image_url: null,
      isActive: true
    },
    {
      id: knex.raw('gen_random_uuid()'),
      name: 'Push-Up',
      slug: 'push-up',
      description: 'Pompe classique.',
      instructions: 'Mains sous les épaules, corps gainé, descendre et pousser.',
      category: 'strength',
      muscle_groups: JSON.stringify(['chest', 'shoulders', 'triceps']),
      difficulty: 'beginner',
      scaling_options: JSON.stringify(['knee push-up', 'incline push-up']),
      equipment_required: JSON.stringify([]),
      bodyweight_only: true,
      measurement_type: 'reps',
      contraindications: JSON.stringify(['douleur épaule', 'douleur poignet']),
      safety_notes: 'Garder les coudes près du corps.',
      video_url: null,
      image_url: null,
      isActive: true
    },
    {
      id: knex.raw('gen_random_uuid()'),
      name: 'Burpee',
      slug: 'burpee',
      description: 'Exercice complet: squat, planche, push-up, saut.',
      instructions: 'Descendre en squat, poser les mains, sauter en planche, push-up, ramener les pieds, sauter.',
      category: 'cardio',
      muscle_groups: JSON.stringify(['full-body']),
      difficulty: 'intermediate',
      scaling_options: JSON.stringify(['step-back burpee', 'no push-up burpee']),
      equipment_required: JSON.stringify([]),
      bodyweight_only: true,
      measurement_type: 'reps',
      contraindications: JSON.stringify(['problème cardiaque']),
      safety_notes: 'Commencer doucement, augmenter progressivement.',
      video_url: null,
      image_url: null,
      isActive: true
    },
    {
      id: knex.raw('gen_random_uuid()'),
      name: 'Box Jump',
      slug: 'box-jump',
      description: 'Saut sur box.',
      instructions: 'Sauter sur la box, extension complète en haut, descendre en contrôle.',
      category: 'gymnastics',
      muscle_groups: JSON.stringify(['legs', 'glutes']),
      difficulty: 'intermediate',
      scaling_options: JSON.stringify(['step-up', 'lower box height']),
      equipment_required: JSON.stringify(['box']),
      bodyweight_only: true,
      measurement_type: 'reps',
      contraindications: JSON.stringify(['douleur genou', 'tendinite achille']),
      safety_notes: 'Atterrir en contrôle, ne pas sauter en arrière.',
      video_url: null,
      image_url: null,
      isActive: true
    },

    // Barbell exercises
    {
      id: knex.raw('gen_random_uuid()'),
      name: 'Back Squat',
      slug: 'back-squat',
      description: 'Squat avec barre sur le dos.',
      instructions: 'Barre sur les trapèzes, descendre en squat, remonter en poussant.',
      category: 'strength',
      muscle_groups: JSON.stringify(['legs', 'glutes', 'core']),
      difficulty: 'intermediate',
      scaling_options: JSON.stringify(['goblet squat', 'front squat']),
      equipment_required: JSON.stringify(['barbell', 'rack']),
      bodyweight_only: false,
      measurement_type: 'weight',
      contraindications: JSON.stringify(['douleur bas du dos']),
      safety_notes: 'Utiliser un rack avec sécurités.',
      video_url: null,
      image_url: null,
      isActive: true
    },
    {
      id: knex.raw('gen_random_uuid()'),
      name: 'Deadlift',
      slug: 'deadlift',
      description: 'Soulevé de terre.',
      instructions: 'Barre au sol, saisir, garder le dos droit, soulever en extension complète.',
      category: 'strength',
      muscle_groups: JSON.stringify(['back', 'legs', 'glutes']),
      difficulty: 'intermediate',
      scaling_options: JSON.stringify(['rack pull', 'kettlebell deadlift']),
      equipment_required: JSON.stringify(['barbell', 'plates']),
      bodyweight_only: false,
      measurement_type: 'weight',
      contraindications: JSON.stringify(['hernie discale']),
      safety_notes: 'Ne jamais arrondir le dos.',
      video_url: null,
      image_url: null,
      isActive: true
    },
    {
      id: knex.raw('gen_random_uuid()'),
      name: 'Bench Press',
      slug: 'bench-press',
      description: 'Développé couché.',
      instructions: 'Allongé sur le banc, barre au niveau de la poitrine, pousser.',
      category: 'strength',
      muscle_groups: JSON.stringify(['chest', 'shoulders', 'triceps']),
      difficulty: 'intermediate',
      scaling_options: JSON.stringify(['dumbbell press', 'incline press']),
      equipment_required: JSON.stringify(['barbell', 'bench']),
      bodyweight_only: false,
      measurement_type: 'weight',
      contraindications: JSON.stringify(['douleur épaule']),
      safety_notes: 'Toujours avoir un pareur ou utiliser des sécurités.',
      video_url: null,
      image_url: null,
      isActive: true
    },
    {
      id: knex.raw('gen_random_uuid()'),
      name: 'Overhead Press',
      slug: 'overhead-press',
      description: 'Développé militaire.',
      instructions: 'Barre aux épaules, pousser au-dessus de la tête, bras tendus.',
      category: 'strength',
      muscle_groups: JSON.stringify(['shoulders', 'triceps', 'core']),
      difficulty: 'intermediate',
      scaling_options: JSON.stringify(['seated press', 'dumbbell press']),
      equipment_required: JSON.stringify(['barbell']),
      bodyweight_only: false,
      measurement_type: 'weight',
      contraindications: JSON.stringify(['douleur épaule']),
      safety_notes: 'Gainer le tronc, ne pas cambrer le dos.',
      video_url: null,
      image_url: null,
      isActive: true
    },

    // Cardio exercises
    {
      id: knex.raw('gen_random_uuid()'),
      name: 'Rowing',
      slug: 'rowing',
      description: 'Rameur.',
      instructions: 'Tirer avec les jambes, puis le dos, puis les bras. Retour inverse.',
      category: 'cardio',
      muscle_groups: JSON.stringify(['full-body']),
      difficulty: 'beginner',
      scaling_options: JSON.stringify(['slower pace', 'shorter distance']),
      equipment_required: JSON.stringify(['rower']),
      bodyweight_only: false,
      measurement_type: 'distance',
      contraindications: JSON.stringify(['douleur bas du dos']),
      safety_notes: 'Garder le dos droit.',
      video_url: null,
      image_url: null,
      isActive: true
    },
    {
      id: knex.raw('gen_random_uuid()'),
      name: 'Assault Bike',
      slug: 'assault-bike',
      description: 'Vélo d\'assaut.',
      instructions: 'Pédaler et pousser/tirer les bras simultanément.',
      category: 'cardio',
      muscle_groups: JSON.stringify(['full-body']),
      difficulty: 'intermediate',
      scaling_options: JSON.stringify(['slower pace', 'arms only', 'legs only']),
      equipment_required: JSON.stringify(['assault-bike']),
      bodyweight_only: false,
      measurement_type: 'calories',
      contraindications: JSON.stringify([]),
      safety_notes: 'Adapter l\'intensité progressivement.',
      video_url: null,
      image_url: null,
      isActive: true
    },
    {
      id: knex.raw('gen_random_uuid()'),
      name: 'Jump Rope',
      slug: 'jump-rope',
      description: 'Corde à sauter.',
      instructions: 'Sauter à la corde, rythme régulier.',
      category: 'cardio',
      muscle_groups: JSON.stringify(['calves', 'shoulders']),
      difficulty: 'beginner',
      scaling_options: JSON.stringify(['single unders', 'slow pace']),
      equipment_required: JSON.stringify(['jump-rope']),
      bodyweight_only: true,
      measurement_type: 'reps',
      contraindications: JSON.stringify(['tendinite achille']),
      safety_notes: 'Surface adaptée, chaussures avec amorti.',
      video_url: null,
      image_url: null,
      isActive: true
    },

    // Kettlebell exercises
    {
      id: knex.raw('gen_random_uuid()'),
      name: 'Kettlebell Swing',
      slug: 'kettlebell-swing',
      description: 'Balancier de kettlebell.',
      instructions: 'Hanche en extension explosive, kettlebell à hauteur des épaules.',
      category: 'strength',
      muscle_groups: JSON.stringify(['glutes', 'hamstrings', 'core']),
      difficulty: 'intermediate',
      scaling_options: JSON.stringify(['lighter weight', 'dumbbell swing']),
      equipment_required: JSON.stringify(['kettlebell']),
      bodyweight_only: false,
      measurement_type: 'reps',
      contraindications: JSON.stringify(['douleur bas du dos']),
      safety_notes: 'Extension de hanche, pas de squat.',
      video_url: null,
      image_url: null,
      isActive: true
    },
    {
      id: knex.raw('gen_random_uuid()'),
      name: 'Turkish Get-Up',
      slug: 'turkish-get-up',
      description: 'Se lever avec kettlebell au-dessus de la tête.',
      instructions: 'Mouvement complexe en 7 étapes du sol à debout.',
      category: 'strength',
      muscle_groups: JSON.stringify(['full-body', 'core', 'shoulders']),
      difficulty: 'advanced',
      scaling_options: JSON.stringify(['no weight', 'lighter weight']),
      equipment_required: JSON.stringify(['kettlebell']),
      bodyweight_only: false,
      measurement_type: 'reps',
      contraindications: JSON.stringify(['douleur épaule']),
      safety_notes: 'Apprendre le mouvement sans charge d\'abord.',
      video_url: null,
      image_url: null,
      isActive: true
    },

    // Core exercises
    {
      id: knex.raw('gen_random_uuid()'),
      name: 'Plank',
      slug: 'plank',
      description: 'Gainage planche.',
      instructions: 'Sur les avant-bras, corps aligné, tenir la position.',
      category: 'strength',
      muscle_groups: JSON.stringify(['core', 'shoulders']),
      difficulty: 'beginner',
      scaling_options: JSON.stringify(['knees down', 'shorter duration']),
      equipment_required: JSON.stringify([]),
      bodyweight_only: true,
      measurement_type: 'time',
      contraindications: JSON.stringify([]),
      safety_notes: 'Ne pas creuser le dos.',
      video_url: null,
      image_url: null,
      isActive: true
    },
    {
      id: knex.raw('gen_random_uuid()'),
      name: 'Sit-Up',
      slug: 'sit-up',
      description: 'Relevé de buste.',
      instructions: 'Allongé sur le dos, pieds fixés, remonter jusqu\'aux genoux.',
      category: 'strength',
      muscle_groups: JSON.stringify(['abs', 'hip-flexors']),
      difficulty: 'beginner',
      scaling_options: JSON.stringify(['crunches', 'assisted sit-up']),
      equipment_required: JSON.stringify([]),
      bodyweight_only: true,
      measurement_type: 'reps',
      contraindications: JSON.stringify(['douleur bas du dos']),
      safety_notes: 'Contrôler la descente.',
      video_url: null,
      image_url: null,
      isActive: true
    }
  ]);
}